// apps/cugetreg-web/src/pages/about/index.tsx
import React from 'react'

import { Box, Card, Link, Typography, useTheme } from '@mui/material'

import { PageMeta } from '@web/components/PageMeta'
import { StyledArticleBody } from '@web/configs/theme/articletext'
import { sessionIdStore } from '@web/store/sessionIdStore'

export default function About() {
  const theme = useTheme()

  const sessionId = sessionIdStore.sessionId
  const reportProblemLink = `https://airtable.com/shruwAAfn1763TgMU?prefill_Session_ID=${sessionId}`

  return (
    <Box marginTop={4} marginBottom={4}>
      <Box sx={{ p: 4, maxWidth: '720px', margin: 'auto' }}>
        <PageMeta title="เกี่ยวกับเรา" />
        <Typography variant="h1">เกี่ยวกับเรา</Typography>
        <Typography variant="h4" component="h2" gutterBottom>
          ชมรม Thinc. จุฬาลงกรณ์มหาวิทยาลัย
        </Typography>
        <StyledArticleBody variant="body1" paragraph>
          ชมรม Thinc. เป็นชมรมที่จัดตั้งและดำเนินการโดยนิสิต โดยสังกัดกรรมการนิสิตคณะวิศวกรรมศาสตร์
          (กวศ.) มีวัตถุประสงค์เพื่อฝึกฝนและฟูมฟักผู้มีความสนใจในการออกแบบและพัฒนาซอฟต์แวร์
          ผ่านการทำโปรเจคพัฒนาซอฟต์แวร์เพื่อสังคมจุฬาฯ
        </StyledArticleBody>
        <StyledArticleBody variant="body1">
          ผลงานที่ผ่านมาของชมรม Thinc. เช่น
          <ul>
            <li>
              <Link
                href="https://book.cusc.chula.ac.th"
                target="_blank"
                rel="noreferrer"
                color={theme.palette.secondaryRange[900]}
              >
                ระบบจองสนามกีฬา CU Sports Center
              </Link>
            </li>
            <li>แอปพลิเคชัน CU Pop Bus</li>
            <li>
              ระบบลงทะเบียนขึ้นสแตนด์แปรอักษรฝั่งจุฬาฯ งานฟุตบอลประเพณีจุฬาฯ-ธรรมศาสตร์ ครั้งที่ 74
            </li>
            <li>Companion App ในงาน JavaScript Bangkok 1.0.0</li>
          </ul>
        </StyledArticleBody>
        <StyledArticleBody variant="body1" paragraph>
          สามารถติดตามชมรม Thinc. ได้ทาง{' '}
          <Link
            href="https://www.facebook.com/ThailandIncubator"
            target="_blank"
            rel="noreferrer"
            color={theme.palette.secondaryRange[900]}
          >
            Facebook Page: Thinc.
          </Link>
        </StyledArticleBody>

        <Typography variant="h4" component="h2" gutterBottom>
          เกี่ยวกับ CU Get Reg
        </Typography>

        <Typography variant="h6" component="h3" gutterBottom>
          ที่มาของโปรเจค
        </Typography>
        <StyledArticleBody variant="body1" paragraph>
          CU Get Reg เกิดมาจาก Pain Point ในการลงทะเบียนเรียนของนิสิตจุฬาฯ
          ที่มักจะต้องลงทะเบียนทั้งวิชาบังคับ วิชาเลือก และวิชาศึกษาทั่วไป (GenEd) ในแต่ละเทอม
          แต่จำเป็นต้องหาข้อมูลจากหลาย ๆ แหล่งที่แตกต่างกัน
          ทั้งยังไม่มีแหล่งใดที่นำเสนอตารางเรียนออกมาเป็นภาพให้เข้าใจง่ายตั้งแต่ก่อนลงทะเบียน
        </StyledArticleBody>
        <StyledArticleBody variant="body1" paragraph>
          ด้วยเหตุนี้ ทางทีมงานจึงได้พัฒนา CU Get Reg ขึ้น
          เพื่อให้สามารถค้นหาและเลือกรายวิชาได้อย่างสะดวก
          และจัดตารางเรียนตามข้อจำกัดของหลักสูตรของแต่ละคนได้ง่ายขึ้น
        </StyledArticleBody>
        <StyledArticleBody variant="body1" paragraph>
          ทางทีมงานมีความมุ่งมั่นที่จะทำให้ CU Get Reg
          เป็นเว็บไซต์ศูนย์กลางที่รวบรวมข้อมูลรายวิชาไว้ได้อย่างครบถ้วน
          และมุ่งที่จะสร้างเว็บไวต์นี้ให้เป็นพื้นที่สำหรับการแบ่งปันข้อมูลรายวิชาระหว่างนิสิตในอนาคต
        </StyledArticleBody>

        <Card variant="outlined" sx={{ marginBottom: 3, padding: 2 }}>
          <StyledArticleBody variant="body1">
            ทั้งนี้ CU Get Reg เป็นเพียงเครื่องมือที่ช่วยให้การวางแผนลงทะเบียนเรียนง่ายขึ้น{' '}
            <strong>
              แต่ไม่ใช่การลงทะเบียนเรียนจริง คุณสามารถลงทะเบียนเรียนได้ที่{' '}
              <Link
                href="https://www2.reg.chula.ac.th/"
                target="_blank"
                rel="noreferrer"
                color={theme.palette.secondaryRange[900]}
              >
                https://www2.reg.chula.ac.th/
              </Link>{' '}
              เพียงช่องทางเดียวเท่านั้น
            </strong>
          </StyledArticleBody>
        </Card>

        <Typography variant="h6" component="h3" gutterBottom>
          CU Get Reg นำข้อมูลมาจากไหน?
        </Typography>
        <StyledArticleBody variant="body1" paragraph>
          <ul>
            <li>
              <strong>ข้อมูลรายวิชาและข้อมูลตอนเรียน:</strong> นำมาจากหน้า{' '}
              <Link
                href="https://cas.reg.chula.ac.th/cu/cs/QueryCourseScheduleNew/index.html"
                target="_blank"
                rel="noreferrer"
                color={theme.palette.secondaryRange[900]}
              >
                สอบถามตารางสอนตารางสอบ
              </Link>{' '}
              ของสำนักงานการทะเบียน ในปัจจุบัน ข้อมูลจากหน้านี้อาจล่าช้าจากข้อมูลภายในระบบ Reg Chula
              ไป 1 วัน ทั้งนี้
              ทีมงานกำลังประสานงานกับสำนักงานการทะเบียนเพื่อเข้าถึงข้อมูลรายวิชาโดยตรง
              เพื่อให้ไม่พบปัญหาดังกล่าว
            </li>
            <li>
              <strong>ข้อมูลตอนเรียนรายวิชา GenEd:</strong> ได้รับข้อมูลจาก Gen อย่าได้ Ed
              และศูนย์การศึกษาทั่วไป
            </li>
            <li>
              <strong>คำอธิบายรายวิชา:</strong> นำมาจาก{' '}
              <Link
                href="http://www.academic.chula.ac.th/search/search.asp"
                target="_blank"
                rel="noreferrer"
                color={theme.palette.secondaryRange[900]}
              >
                ระบบค้นหาคำอธิบายรายวิชา
              </Link>{' '}
              ของสำนักบริหารวิชาการ จุฬาฯ
            </li>
          </ul>
        </StyledArticleBody>

        <Typography variant="h6" component="h3" gutterBottom>
          การเข้าสู่ระบบ มีประโยชน์อย่างไรบ้าง?
        </Typography>
        <StyledArticleBody variant="body1" paragraph>
          เมื่อคุณเข้าสู่ระบบ ระบบจะบันทึกข้อมูลตารางเรียนไว้ในบัญชี Google ของคุณ
          ทำให้สามารถเข้าสู่ระบบเพื่อดูข้อมูลตารางเรียนที่เลือกไว้ข้ามอุปกรณ์ได้
          รวมถึงเป็นการยืนยันตัวตนเพื่อเขียนรีวิวรายวิชาที่คุณเรียนมา
        </StyledArticleBody>
        <StyledArticleBody variant="body1" paragraph>
          ในการเข้าสู่ระบบ สามารถใช้บัญชีอีเมลนิสิต (รหัสนิสิต@student.chula.ac.th) เท่านั้น
          เพื่อให้สามารถยืนยันตัวตนได้ว่าเป็นนิสิตจุฬาฯ
        </StyledArticleBody>
        <StyledArticleBody variant="body1" paragraph>
          หากต้องการทราบว่าเราเก็บข้อมูลใดและนำไปใช้อย่างไรบ้าง สามารถอ่านเพิ่มเติมได้ที่{' '}
          <Link
            href="/privacy"
            target="_blank"
            rel="noreferrer"
            color={theme.palette.secondaryRange[900]}
          >
            Privacy Policy
          </Link>{' '}
          ของเรา
        </StyledArticleBody>

        <Typography variant="h6" component="h3" gutterBottom>
          ความร่วมมือกับหน่วยงานอื่น ๆ
        </Typography>
        <StyledArticleBody variant="body1" paragraph>
          CU Get Reg มีความร่วมมือกับหน่วยงานอื่นภายในจุฬาฯ ได้แก่
          <ul>
            <li>
              <strong>สำนักงานการทะเบียน (Reg Chula):</strong> CU Get Reg
              ได้รับการสนับสนุนเซิร์ฟเวอร์จากสำนักงานการทะเบียน นอกจากนี้
              ทางสำนักงานการทะเบียนยังพร้อมให้ความสนับสนุนในด้านข้อมูลรายวิชา
              ซึ่งกำลังอยู่ในระหว่างดำเนินการ{' '}
              <Link
                href="https://www.reg.chula.ac.th/"
                target="_blank"
                rel="noreferrer"
                color={theme.palette.secondaryRange[900]}
              >
                (เว็บไซต์ สำนักงานการทะเบียน)
              </Link>
            </li>
            <li>
              <strong>Gen อย่าได้ Ed:</strong> ปัจจุบันร่วมมือกับ CU Get Reg
              ในการประชาสัมพันธ์เว็บไซต์ให้กับนิสิตจุฬาฯ{' '}
              <Link
                href="https://www.facebook.com/genedahs"
                target="_blank"
                rel="noreferrer"
                color={theme.palette.secondaryRange[900]}
              >
                (Facebook Page: Gen อย่าได้ Ed)
              </Link>
            </li>
            <li>
              <strong>ศูนย์การศึกษาทั่วไป (GenEd Chula):</strong> CU Get Reg
              ได้รับการสนับสนุนจากศูนย์การศึกษาทั่วไปในด้านข้อมูลรายวิชาศึกษาทั่วไป (GenEd){' '}
              <Link
                href="https://www.gened.chula.ac.th/c/"
                target="_blank"
                rel="noreferrer"
                color={theme.palette.secondaryRange[900]}
              >
                (เว็บไซต์ ศูนย์การศึกษาทั่วไป)
              </Link>
            </li>
          </ul>
        </StyledArticleBody>

        <Typography variant="h4" component="h2" gutterBottom>
          ติดต่อทีมงาน
        </Typography>
        <StyledArticleBody variant="body1" paragraph>
          สามารถแจ้งปัญหาขัดข้องเกี่ยวกับการใช้งานเว็บไซต์ ข้อมูลที่ไม่ถูกต้อง หรือข้อเสนอแนะต่าง ๆ
          ได้ทาง{' '}
          <Link
            href={reportProblemLink}
            target="_blank"
            rel="noreferrer"
            color={theme.palette.secondaryRange[900]}
          >
            ฟอร์มแจ้งปัญหา
          </Link>{' '}
          ที่มุมบนขวาของหน้าเว็บ
        </StyledArticleBody>
        <StyledArticleBody variant="body1" paragraph>
          หากต้องการติดต่อสอบถามเกี่ยวกับเว็บไซต์ CU Get Reg หรือติดต่อชมรม Thinc. สามารถสอบถามทาง{' '}
          <Link
            href="https://www.facebook.com/ThailandIncubator"
            target="_blank"
            rel="noreferrer"
            color={theme.palette.secondaryRange[900]}
          >
            Facebook Page: Thinc.
          </Link>{' '}
          ได้โดยตรง
        </StyledArticleBody>
      </Box>
    </Box>
  )
}

// frontend/src/pages/About.svelte
<script lang="ts">
    import { Globe } from "lucide-svelte";
    import GitHubMark from "../lib/components/logo/vendor/GitHubMark.svelte";
    import Facebook from "../lib/components/logo/facebook/facebook.svelte";

    import { QuestionAnswer } from "../lib/components/atoms/faqs";
    import Footer from "../lib/components/organisms/footer/footer.svelte";
    import Navbar from "../lib/components/organisms/navbar/navbar.svelte";
    import Instagram from "../lib/components/logo/instagram/instagram.svelte";
</script>

<Navbar />

<div class="py-12 flex justify-center">
    <div class="w-[80%] min-w-[60vw]">
        <div class="text-3xl font-bold">เกี่ยวกับเรา</div>

        <div class="flex my-5">
            <div class="flex-1 text-lg font-bold">
                <div>ชมรม Thinc.</div>
                <div>จุฬาลงกรณ์มหาวิทยาลัย</div>
            </div>
            <div lang="th" class="flex-1 font-sarabun wrap-break-word">
                ชมรม Thinc. เป็นชมรมที่จัดตั้งและดำเนินการโดยนิสิต
                โดยสังกัดกรรมการนิสิตคณะวิศวกรรมศาสตร์ (กวศ.)
                มีวัตถุประสงค์เพื่อฝึกฝนและฟูมฟักผู้มีความสนใจในการออกแบบและพัฒนาซอฟต์แวร์
                ผ่านการทำโปรเจคพัฒนาซอฟต์แวร์เพื่อสังคมจุฬาฯ
                ผลงานที่ผ่านมาของชมรม Thinc. เช่น
                <ul class="list-disc pl-5">
                    <li>
                        ระบบจองสนามกีฬา CU Sports Center แอปพลิเคชัน CU Pop Bus
                    </li>
                    <li>ระบบลงทะเบียนขึ้นสแตนด์แปรอักษรฝั่งจุฬาฯ</li>
                    <li>
                        งานฟุตบอลประเพณีจุฬาฯ-ธรรมศาสตร์ ครั้งที่ 74 Companion
                        App ในงาน
                    </li>
                    <li>JavaScript Bangkok 1.0.0</li>
                </ul>
            </div>
        </div>

        <div class="text-2xl font-bold">เกี่ยวกับ CU Get Reg</div>

        <QuestionAnswer question="ที่มาของโปรเจค">
            CU Get Reg เกิดมาจาก Pain Point ในการลงทะเบียนเรียนของนิสิตจุฬาฯ
            ที่มักจะต้องลงทะเบียนทั้งวิชาบังคับ วิชาเลือก และวิชาศึกษาทั่วไป
            (GenEd) ในแต่ละเทอม แต่จำเป็นต้องหาข้อมูลจากหลาย ๆ
            แหล่งที่แตกต่างกัน
            ทั้งยังไม่มีแหล่งใดที่นำเสนอตารางเรียนออกมาเป็นภาพให้เข้าใจง่ายตั้งแต่ก่อนลงทะเบียน
            ด้วยเหตุนี้ ทางทีมงานจึงได้พัฒนา CU Get Reg ขึ้น
            เพื่อให้สามารถค้นหาและเลือกรายวิชาได้อย่างสะดวก
            และจัดตารางเรียนตามข้อจำกัดของหลักสูตรของแต่ละคนได้ง่ายขึ้น
            ทางทีมงานมีความมุ่งมั่นที่จะทำให้ CU Get Reg
            เป็นเว็บไซต์ศูนย์กลางที่รวบรวมข้อมูลรายวิชาไว้ได้อย่างครบถ้วน
            และมุ่งที่จะสร้างเว็บไวต์นี้ให้เป็นพื้นที่สำหรับการแบ่งปันข้อมูลรายวิชาระหว่างนิสิตในอนาคต
        </QuestionAnswer>
        <QuestionAnswer question="CU Get Reg นำข้อมูลมาจากไหน?">
            <ul class="list-disc">
                <li>
                    ข้อมูลรายวิชาและข้อมูลตอนเรียน: นำมาจากหน้า 
                    <a
                        href="https://cas.reg.chula.ac.th/cu/cs/QueryCourseScheduleNew/index.html"
                        class="link"
                    >
                        สอบถามตารางสอนตารางสอบ
                    </a>
                    ของสำนักงานการทะเบียน
                </li>
                <li>
                    ในปัจจุบัน ข้อมูลจากหน้านี้อาจล่าช้าจากข้อมูลภายในระบบ Reg
                    Chula ไป 1 วัน ทั้งนี้
                    ทีมงานกำลังประสานงานกับสำนักงานการทะเบียนเพื่อเข้าถึงข้อมูลรายวิชาโดยตรง
                    เพื่อให้ไม่พบปัญหาดังกล่าว
                </li>
                <li>
                    ข้อมูลตอนเรียนรายวิชา GenEd: ได้รับข้อมูลจาก Gen อย่าได้ Ed
                    และศูนย์การศึกษาทั่วไป
                </li>
                <li>
                    คำอธิบายรายวิชา: นำมาจาก ระบบค้นหาคำอธิบายรายวิชา ของสำนักบริหารวิชาการ
                    จุฬาฯ
                </li>
            </ul>
        </QuestionAnswer>

        <QuestionAnswer question="การเข้าสู่ระบบ มีประโยชน์อย่างไรบ้าง?">
            เมื่อคุณเข้าสู่ระบบ ระบบจะบันทึกข้อมูลตารางเรียนไว้ในบัญชี Google
            ของคุณ
            ทำให้สามารถเข้าสู่ระบบเพื่อดูข้อมูลตารางเรียนที่เลือกไว้ข้ามอุปกรณ์ได้
            รวมถึงเป็นการยืนยันตัวตนเพื่อเขียนรีวิวรายวิชาที่คุณเรียนมา
            ในการเข้าสู่ระบบ สามารถใช้บัญชีอีเมลนิสิต
            (รหัสนิสิต@student.chula.ac.th) เท่านั้น
            เพื่อให้สามารถยืนยันตัวตนได้ว่าเป็นนิสิตจุฬาฯ
            หากต้องการทราบว่าเราเก็บข้อมูลใดและนำไปใช้อย่างไรบ้าง
            สามารถอ่านเพิ่มเติมได้ที่ <a
                href="/privacy"
                class="link">Privacy Policy</a
            > ของเรา
        </QuestionAnswer>

        <QuestionAnswer question="ความร่วมมือกับหน่วยงานอื่น ๆ">
            CU Get Reg มีความร่วมมือกับหน่วยงานอื่นภายในจุฬาฯ ได้แก่
            <ul class="list-disc">
                <li>
                    สำนักงานการทะเบียน (Reg Chula): CU Get Reg
                    ได้รับการสนับสนุนเซิร์ฟเวอร์จากสำนักงานการทะเบียน นอกจากนี้
                    ทางสำนักงานการทะเบียนยังพร้อมให้ความสนับสนุนในด้านข้อมูลรายวิชา
                    ซึ่งกำลังอยู่ในระหว่างดำเนินการ  
                    <br />
                    <a href="reg.chula.ac.th" class="link"
                        >(เว็บไซต์ สำนักงานการทะเบียน)</a
                    >
                </li>
                <li>
                    Gen อย่าได้ Ed: ปัจจุบันร่วมมือกับ CU Get Reg
                    ในการประชาสัมพันธ์เว็บไซต์ให้กับนิสิตจุฬาฯ 
                    <br />
                    <a href="https://www.facebook.com/genedahs" class="link"
                        >(Facebook Page: Gen อย่าได้ Ed)</a
                    >
                </li>
                <li>
                    ศูนย์การศึกษาทั่วไป (GenEd Chula): CU Get Reg
                    ได้รับการสนับสนุนจากศูนย์การศึกษาทั่วไปในด้านข้อมูลรายวิชาศึกษาทั่วไป
                    (GenEd) 
                    <br />
                    <a href="https://www.gened.chula.ac.th" class="link"
                        >(เว็บไซต์ ศูนย์การศึกษาทั่วไป)</a
                    >
                </li>
            </ul>
        </QuestionAnswer>

        <QuestionAnswer question="ติดต่อทีมงาน">
            สามารถแจ้งปัญหาขัดข้องเกี่ยวกับการใช้งานเว็บไซต์ ข้อมูลที่ไม่ถูกต้อง
            หรือข้อเสนอแนะต่าง ๆ ได้ทาง <a class="link">ฟอร์มแจ้งปัญหา</a>
            ที่มุมบนขวาของหน้าเว็บ หากต้องการติดต่อสอบถามเกี่ยวกับเว็บไซต์ CU Get
            Reg หรือติดต่อชมรม Thinc. สามารถสอบถามทาง 
            <a href="https://www.facebook.com/ThailandIncubator" class="link"
                >Facebook Page: Thinc.</a
            >
            ได้โดยตรง

            <ul class="list-normal mt-2 space-y-3 fill-blue-700">
                <li class="flex items-center">
                    <Globe class="w-[2em] h-[2em] m-2 stroke-blue-700" />
                    <a class="link" href="thinc.in.th">https://thinc.in.th</a>
                </li>
                <li class="flex items-center">
                    <Facebook class="w-[2em] h-[2em] m-2" />
                    <a
                        class="link"
                        href="https://www.facebook.com/ThailandIncubator"
                        >Facebook: Thinc.</a
                    >
                </li>
                <li class="flex items-center">
                    <GitHubMark class="w-[2em] h-[2em] m-2" />
                    <a class="link" href="https://github.com/thinc-org"
                        >GitHub: Thinc.</a
                    >
                </li>
                <li class="flex items-center">
                    <Instagram class="w-[2em] h-[2em] m-2" />
                    <a class="link" href="https://www.instagram.com/thinc.in.th/"
                        >Instagram: Thinc.</a
                    >
                </li>
            </ul>
        </QuestionAnswer>
    </div>
</div>

<Footer />

<style>
    @reference "../app.css";

    .link {
        @apply text-blue-700 underline;
    }
</style>
